version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps)"
    groups:
      prisma:
        patterns:
          - "prisma"
          - "@prisma/*"
          - "@neondatabase/*"
      eslint-prettier:
        patterns:
          - "eslint*"
          - "prettier"
          - "@types/eslint"
          - "@typescript-eslint/*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps)"
