name: Migrate Databases

on:
  workflow_dispatch:

jobs:
  install_deps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Install dependencies
        run: yarn
  
  db_migrate:
    needs: [install_deps]

    runs-on: ubuntu-latest

    strategy:
      matrix:
        database_url: [DATABASE_URL, DATABASE_URL]

    steps:
      - uses: actions/checkout@v4

      - name: Set DATABASE_URL .env-variables
        run: |
          touch .env
          echo DATABASE_URL=${{ secrets[matrix.database_url] }} >> .env

      - name: Migrate
        run: npx prisma migrate deploy
