# Two roles:
# 1. Runs often to avoid Supabase to enter sleep-mode (https://supabase.com/docs/going-into-prod#availability)
# 2. Updates the player-table in the database with the memberships on TIHLDE.org
#
# An auth token from tihlde.org MUST be set as a secret in TIHLDE_AUTH_TOKEN
# Since that is needed at the /api/refresh-players endpoint
name: Update users

on:
  schedule:
    - cron: 0 * * * *
  workflow_dispatch:

jobs:
  render:
    name: Render website
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Stage
        id: request
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://pythons.tihlde.org/api/refresh-players'
          method: 'POST'
          timeout: 20000
          data: '{"authToken": "${{ secrets.TIHLDE_AUTH_TOKEN }}"}'
      - name: Respons
        run: |
          echo ${{ steps.request.outputs.response }}
