# Used to avoid Supabase to enter sleep-mode (https://supabase.com/docs/going-into-prod#availability)
name: Render website

on:
  push:
    branches:
      - feat/supabase

# on:
#   schedule:
#     - cron: 0 12 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Fetch URL
        uses: boyeborg/fetch-url-action@v1.1
        with:
          url: https://pythons.tihlde.org
      # - name: Render website
        # run: |
          # xdg-open https://pythons.tihlde.org && sleep 10
